// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnf7_swGrmx-pd4uvf4YKWskaLv_6IqU',
    appId: '1:132851206607:web:f7b51b61f8da276e3feaba',
    messagingSenderId: '132851206607',
    projectId: 'mamicarep',
    authDomain: 'mamicarep.firebaseapp.com',
    storageBucket: 'mamicarep.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHR3Yeg1tZlWkaM-wxDB87shqdQn_EByk',
    appId: '1:132851206607:android:dbcf49dc20e013273feaba',
    messagingSenderId: '132851206607',
    projectId: 'mamicarep',
    storageBucket: 'mamicarep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNMdv4HgF-14UQnNJrTOJmHC2dYrACAfI',
    appId: '1:132851206607:ios:1a721f33a53bd7113feaba',
    messagingSenderId: '132851206607',
    projectId: 'mamicarep',
    storageBucket: 'mamicarep.firebasestorage.app',
    iosBundleId: 'com.example.mamicarePlus2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNMdv4HgF-14UQnNJrTOJmHC2dYrACAfI',
    appId: '1:132851206607:ios:1a721f33a53bd7113feaba',
    messagingSenderId: '132851206607',
    projectId: 'mamicarep',
    storageBucket: 'mamicarep.firebasestorage.app',
    iosBundleId: 'com.example.mamicarePlus2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMnf7_swGrmx-pd4uvf4YKWskaLv_6IqU',
    appId: '1:132851206607:web:8443b4f54eacd6ff3feaba',
    messagingSenderId: '132851206607',
    projectId: 'mamicarep',
    authDomain: 'mamicarep.firebaseapp.com',
    storageBucket: 'mamicarep.firebasestorage.app',
  );
}
